#!/usr/bin/env python3
"""Compile a MeetingNote JSON into Markdown or self-contained HTML (stdlib only).

Usage:
    compile.py meeting.json -o meeting.md
    compile.py meeting.json -f html -o meeting.html
    compile.py meeting.json --lang en --tz UTC

Ported from meeting-note's compile/ package; the HTML output reproduces the
same self-contained template without the Jinja2 dependency.
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

LABELS = {
    "ja": {
        "date": "日時",
        "duration": "所要時間",
        "minutes_suffix": "分",
        "type": "種別",
        "context": "背景",
        "participants": "参加者",
        "participants_cols": ["氏名", "役割", "所属"],
        "dynamics": "参加者間の関係性",
        "dynamics_cols": ["発信者", "受信者", "関係", "議題", "詳細"],
        "agenda": "議題",
        "summary": "概要",
        "speakers": "発言者",
        "discussion_points": "議論のポイント",
        "decisions": "決定事項",
        "decision": "決定",
        "why": "理由",
        "alternatives": "検討された代替案",
        "decided_by": "決定者",
        "action_items": "アクションアイテム",
        "action_cols": ["担当者", "タスク", "期限", "背景"],
        "unresolved": "未解決事項",
        "unresolved_cols": ["課題", "ブロッカー", "持ち越し先"],
        "takeaways": "主要な結論",
        "generated": "{by} により自動生成",
        "status": {
            "decided": "[決定]",
            "pending": "[保留]",
            "rejected": "[却下]",
            "informational": "[情報共有]",
        },
        "meeting_type": {
            "regular": "定例",
            "ad_hoc": "臨時",
            "review": "レビュー",
            "decision": "意思決定",
            "informational": "情報共有",
        },
        "role": {
            "organizer": "主催者",
            "decision_maker": "意思決定者",
            "proposer": "提案者",
            "reporter": "報告者",
            "observer": "オブザーバー",
        },
        "relation": {
            "proposal_approval": "提案 → 承認",
            "objection_reproposal": "反論 → 再提案",
            "delegation": "委任",
            "question_answer": "質疑応答",
            "report": "報告",
            "instruction": "指示",
        },
    },
    "en": {
        "date": "Date",
        "duration": "Duration",
        "minutes_suffix": " min",
        "type": "Type",
        "context": "Context",
        "participants": "Participants",
        "participants_cols": ["Name", "Role", "Affiliation"],
        "dynamics": "Participant Dynamics",
        "dynamics_cols": ["From", "To", "Relation", "Topic", "Detail"],
        "agenda": "Agenda",
        "summary": "Summary",
        "speakers": "Speakers",
        "discussion_points": "Discussion Points",
        "decisions": "Decisions",
        "decision": "Decision",
        "why": "Rationale",
        "alternatives": "Alternatives considered",
        "decided_by": "Decided by",
        "action_items": "Action Items",
        "action_cols": ["Owner", "Task", "Due", "Context"],
        "unresolved": "Unresolved",
        "unresolved_cols": ["Issue", "Blocker", "Carried forward to"],
        "takeaways": "Key Takeaways",
        "generated": "Generated by {by}",
        "status": {
            "decided": "[Decided]",
            "pending": "[Pending]",
            "rejected": "[Rejected]",
            "informational": "[Info]",
        },
        "meeting_type": {
            "regular": "Regular",
            "ad_hoc": "Ad hoc",
            "review": "Review",
            "decision": "Decision",
            "informational": "Informational",
        },
        "role": {
            "organizer": "Organizer",
            "decision_maker": "Decision maker",
            "proposer": "Proposer",
            "reporter": "Reporter",
            "observer": "Observer",
        },
        "relation": {
            "proposal_approval": "Proposal → Approval",
            "objection_reproposal": "Objection → Reproposal",
            "delegation": "Delegation",
            "question_answer": "Q&A",
            "report": "Report",
            "instruction": "Instruction",
        },
    },
}


def parse_datetime(value: str) -> datetime | None:
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except (ValueError, AttributeError):
        return None


def format_date(value: str) -> str:
    dt = parse_datetime(value)
    return dt.strftime("%Y-%m-%d %H:%M") if dt else value


def format_generated_at(note: dict, tz: str) -> str:
    dt = parse_datetime(note.get("metadata", {}).get("generated_at", ""))
    if not dt:
        return ""
    return dt.astimezone(ZoneInfo(tz)).strftime("%Y-%m-%d %H:%M:%S")


# --- Markdown ---------------------------------------------------------------


def _cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", "<br>")


def render_markdown(note: dict, *, lang: str = "ja", tz: str = "Asia/Tokyo") -> str:
    L = LABELS[lang]
    lines: list[str] = [f"# {note.get('title', '')}", ""]

    lines.append(f"- **{L['date']}**: {format_date(note.get('date', ''))}")
    if note.get("duration_seconds"):
        lines.append(
            f"- **{L['duration']}**: {note['duration_seconds'] // 60}{L['minutes_suffix']}"
        )
    if note.get("meeting_type"):
        label = L["meeting_type"].get(note["meeting_type"], note["meeting_type"])
        lines.append(f"- **{L['type']}**: {label}")
    if note.get("context"):
        lines.append(f"- **{L['context']}**: {note['context']}")
    lines.append("")

    if note.get("participants"):
        cols = L["participants_cols"]
        lines += [f"## {L['participants']}", "", f"| {' | '.join(cols)} |",
                  f"|{'|'.join('------' for _ in cols)}|"]
        for p in note["participants"]:
            role = L["role"].get(p.get("role", ""), p.get("role") or "")
            lines.append(
                f"| {_cell(p.get('name', ''))} | {_cell(role)} | {_cell(p.get('affiliation', ''))} |"
            )
        lines.append("")

    if note.get("participant_dynamics"):
        cols = L["dynamics_cols"]
        lines += [f"## {L['dynamics']}", "", f"| {' | '.join(cols)} |",
                  f"|{'|'.join('------' for _ in cols)}|"]
        for d in note["participant_dynamics"]:
            relation = L["relation"].get(d.get("relation", ""), d.get("relation", ""))
            lines.append(
                f"| {_cell(d.get('from', ''))} | {_cell(d.get('to', ''))} "
                f"| {_cell(relation)} | {_cell(d.get('topic', ''))} "
                f"| {_cell(d.get('detail', ''))} |"
            )
        lines.append("")

    if note.get("agenda"):
        lines += [f"## {L['agenda']}", ""]
        for i, item in enumerate(note["agenda"], 1):
            status = L["status"].get(item.get("status", ""), "")
            lines += [f"### {i}. {item.get('title', '')} {status}", ""]

            if item.get("summary"):
                lines += [f"**{L['summary']}**: {item['summary']}", ""]
            if item.get("speakers"):
                lines += [f"**{L['speakers']}**: {', '.join(item['speakers'])}", ""]

            if item.get("discussion_points"):
                lines += [f"#### {L['discussion_points']}", ""]
                lines += [f"- {point}" for point in item["discussion_points"]]
                lines.append("")

            if item.get("decisions"):
                lines += [f"#### {L['decisions']}", ""]
                for decision in item["decisions"]:
                    lines += [f"**{L['decision']}**: {decision.get('what', '')}", ""]
                    if decision.get("why"):
                        lines += [f"> **{L['why']}**: {decision['why']}", ""]
                    if decision.get("alternatives_considered"):
                        lines += [f"**{L['alternatives']}**:", ""]
                        lines += [
                            f"- ~~{alt.get('option', '')}~~ -- {alt.get('rejected_because', '')}"
                            for alt in decision["alternatives_considered"]
                        ]
                        lines.append("")
                    if decision.get("decided_by"):
                        lines += [f"**{L['decided_by']}**: {', '.join(decision['decided_by'])}", ""]

            if item.get("action_items"):
                cols = L["action_cols"]
                lines += [f"#### {L['action_items']}", "", f"| {' | '.join(cols)} |",
                          f"|{'|'.join('------' for _ in cols)}|"]
                for ai in item["action_items"]:
                    lines.append(
                        f"| {_cell(ai.get('owner', ''))} | {_cell(ai.get('task', ''))} "
                        f"| {_cell(ai.get('due', ''))} | {_cell(ai.get('context', ''))} |"
                    )
                lines.append("")

            if item.get("unresolved"):
                cols = L["unresolved_cols"]
                lines += [f"#### {L['unresolved']}", "", f"| {' | '.join(cols)} |",
                          f"|{'|'.join('------' for _ in cols)}|"]
                for u in item["unresolved"]:
                    lines.append(
                        f"| {_cell(u.get('issue', ''))} | {_cell(u.get('blocker', ''))} "
                        f"| {_cell(u.get('carry_forward_to', ''))} |"
                    )
                lines.append("")

    if note.get("key_takeaways"):
        lines += [f"## {L['takeaways']}", ""]
        lines += [f"- {t}" for t in note["key_takeaways"]]
        lines.append("")

    lines += ["---", ""]
    generated_by = note.get("metadata", {}).get("generated_by", "")
    if generated_by:
        generated_at = format_generated_at(note, tz)
        suffix = f" ({generated_at})" if generated_at else ""
        lines += [f"*{L['generated'].format(by=generated_by)}{suffix}*", ""]

    return "\n".join(lines)


# --- HTML -------------------------------------------------------------------

_CSS = """\
:root {
  --color-bg: #ffffff;
  --color-text: #1a1a2e;
  --color-muted: #6b7280;
  --color-border: #e5e7eb;
  --color-card-bg: #f9fafb;
  --color-decided: #059669;
  --color-decided-bg: #ecfdf5;
  --color-pending: #d97706;
  --color-pending-bg: #fffbeb;
  --color-rejected: #dc2626;
  --color-rejected-bg: #fef2f2;
  --color-informational: #6366f1;
  --color-informational-bg: #eef2ff;
  --color-why-bg: #f0f9ff;
  --color-why-border: #0284c7;
  --gap: 1rem;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Hiragino Sans", "Noto Sans JP", sans-serif;
  color: var(--color-text);
  background: var(--color-bg);
  line-height: 1.6;
  max-width: 960px;
  margin: 0 auto;
  padding: 2rem var(--gap);
}
h1 { font-size: 1.75rem; margin-bottom: 0.5rem; }
h2 { font-size: 1.35rem; margin: 1.5rem 0 0.75rem; border-bottom: 2px solid var(--color-border); padding-bottom: 0.25rem; }
h3 { font-size: 1.1rem; margin: 1rem 0 0.5rem; }
h4 { font-size: 0.95rem; margin: 0.75rem 0 0.25rem; color: var(--color-muted); }
.meta { color: var(--color-muted); font-size: 0.9rem; margin-bottom: 1.5rem; }
.meta span { margin-right: 1.5rem; }
table { width: 100%; border-collapse: collapse; margin: 0.5rem 0 1rem; font-size: 0.9rem; }
th, td { padding: 0.5rem 0.75rem; text-align: left; border: 1px solid var(--color-border); }
th { background: var(--color-card-bg); font-weight: 600; }
.badge {
  display: inline-block;
  padding: 0.15rem 0.5rem;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.03em;
  vertical-align: middle;
}
.badge-decided { color: var(--color-decided); background: var(--color-decided-bg); }
.badge-pending { color: var(--color-pending); background: var(--color-pending-bg); }
.badge-rejected { color: var(--color-rejected); background: var(--color-rejected-bg); }
.badge-informational { color: var(--color-informational); background: var(--color-informational-bg); }
.agenda-card {
  background: var(--color-card-bg);
  border: 1px solid var(--color-border);
  border-radius: 8px;
  padding: var(--gap);
  margin: var(--gap) 0;
}
.agenda-header { display: flex; align-items: center; gap: 0.5rem; cursor: pointer; }
.agenda-header h3 { margin: 0; flex: 1; }
.agenda-body { margin-top: var(--gap); }
.why-box {
  background: var(--color-why-bg);
  border-left: 4px solid var(--color-why-border);
  padding: 0.75rem 1rem;
  margin: 0.5rem 0;
  border-radius: 0 4px 4px 0;
}
.why-box strong { color: var(--color-why-border); }
.alt-rejected { text-decoration: line-through; color: var(--color-muted); }
.decision-block { margin: 0.75rem 0; }
ul, ol { padding-left: 1.5rem; margin: 0.25rem 0; }
li { margin: 0.25rem 0; }
.takeaways li { margin: 0.5rem 0; }
.footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--color-border); color: var(--color-muted); font-size: 0.8rem; }
@media print {
  body { max-width: 100%; padding: 1rem; }
  .agenda-body { display: block !important; }
  .toggle-icon { display: none; }
}
@media (max-width: 640px) {
  body { padding: 1rem 0.5rem; }
  table { font-size: 0.8rem; }
  th, td { padding: 0.35rem 0.5rem; }
}
"""

_TOGGLE = (
    "this.parentElement.querySelector('.agenda-body').style.display = "
    "this.parentElement.querySelector('.agenda-body').style.display === 'none' "
    "? 'block' : 'none'"
)


def _esc(text: str) -> str:
    return html.escape(str(text), quote=True)


def _table(headers: list[str], rows: list[list[str]]) -> list[str]:
    out = ["<table>", "  <thead><tr>" + "".join(f"<th>{_esc(h)}</th>" for h in headers) + "</tr></thead>", "  <tbody>"]
    for row in rows:
        out.append("    <tr>" + "".join(f"<td>{_esc(c)}</td>" for c in row) + "</tr>")
    out += ["  </tbody>", "</table>"]
    return out


def render_html(note: dict, *, lang: str = "ja", tz: str = "Asia/Tokyo") -> str:
    L = LABELS[lang]
    o: list[str] = [
        "<!DOCTYPE html>",
        f'<html lang="{lang}">',
        "<head>",
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        f"<title>{_esc(note.get('title', ''))}</title>",
        "<style>",
        _CSS,
        "</style>",
        "</head>",
        "<body>",
        "",
        f"<h1>{_esc(note.get('title', ''))}</h1>",
        '<div class="meta">',
        f"  <span>{_esc(format_date(note.get('date', '')))}</span>",
    ]
    if note.get("duration_seconds"):
        o.append(f"  <span>{note['duration_seconds'] // 60}{_esc(L['minutes_suffix'])}</span>")
    if note.get("meeting_type"):
        label = L["meeting_type"].get(note["meeting_type"], note["meeting_type"])
        o.append(f"  <span>{_esc(label)}</span>")
    if note.get("context"):
        o.append(f"  <span>{_esc(note['context'])}</span>")
    o.append("</div>")

    if note.get("participants"):
        o.append(f"<h2>{_esc(L['participants'])}</h2>")
        o += _table(
            L["participants_cols"],
            [
                [p.get("name", ""), L["role"].get(p.get("role", ""), p.get("role") or ""), p.get("affiliation", "")]
                for p in note["participants"]
            ],
        )

    if note.get("participant_dynamics"):
        o.append(f"<h2>{_esc(L['dynamics'])}</h2>")
        o += _table(
            L["dynamics_cols"],
            [
                [
                    d.get("from", ""),
                    d.get("to", ""),
                    L["relation"].get(d.get("relation", ""), d.get("relation", "")),
                    d.get("topic", ""),
                    d.get("detail", ""),
                ]
                for d in note["participant_dynamics"]
            ],
        )

    if note.get("agenda"):
        o.append(f"<h2>{_esc(L['agenda'])}</h2>")
        for i, item in enumerate(note["agenda"], 1):
            status = item.get("status", "")
            status_label = L["status"].get(status, status)
            o += [
                '<div class="agenda-card">',
                f'  <div class="agenda-header" onclick="{_TOGGLE}">',
                f"    <h3>{i}. {_esc(item.get('title', ''))}</h3>",
                f'    <span class="badge badge-{_esc(status)}">{_esc(status_label)}</span>',
                '    <span class="toggle-icon">&#9660;</span>',
                "  </div>",
                '  <div class="agenda-body">',
            ]
            if item.get("summary"):
                o.append(f"    <p>{_esc(item['summary'])}</p>")
            if item.get("speakers"):
                o.append(
                    f"    <p><strong>{_esc(L['speakers'])}</strong>: {_esc(', '.join(item['speakers']))}</p>"
                )
            if item.get("discussion_points"):
                o.append(f"    <h4>{_esc(L['discussion_points'])}</h4>")
                o.append("    <ul>")
                o += [f"      <li>{_esc(point)}</li>" for point in item["discussion_points"]]
                o.append("    </ul>")
            if item.get("decisions"):
                o.append(f"    <h4>{_esc(L['decisions'])}</h4>")
                for decision in item["decisions"]:
                    o += [
                        '    <div class="decision-block">',
                        f"      <p><strong>{_esc(decision.get('what', ''))}</strong></p>",
                    ]
                    if decision.get("why"):
                        o += [
                            '      <div class="why-box">',
                            f"        <strong>{_esc(L['why'])}:</strong> {_esc(decision['why'])}",
                            "      </div>",
                        ]
                    if decision.get("alternatives_considered"):
                        o.append(f"      <p><strong>{_esc(L['alternatives'])}:</strong></p>")
                        o.append("      <ul>")
                        o += [
                            f'        <li><span class="alt-rejected">{_esc(alt.get("option", ""))}</span>'
                            f" &mdash; {_esc(alt.get('rejected_because', ''))}</li>"
                            for alt in decision["alternatives_considered"]
                        ]
                        o.append("      </ul>")
                    if decision.get("decided_by"):
                        o.append(
                            f"      <p><strong>{_esc(L['decided_by'])}:</strong> {_esc(', '.join(decision['decided_by']))}</p>"
                        )
                    o.append("    </div>")
            if item.get("action_items"):
                o.append(f"    <h4>{_esc(L['action_items'])}</h4>")
                o += _table(
                    L["action_cols"],
                    [
                        [ai.get("owner", ""), ai.get("task", ""), ai.get("due", ""), ai.get("context", "")]
                        for ai in item["action_items"]
                    ],
                )
            if item.get("unresolved"):
                o.append(f"    <h4>{_esc(L['unresolved'])}</h4>")
                o += _table(
                    L["unresolved_cols"],
                    [
                        [u.get("issue", ""), u.get("blocker", ""), u.get("carry_forward_to", "")]
                        for u in item["unresolved"]
                    ],
                )
            o += ["  </div>", "</div>"]

    if note.get("key_takeaways"):
        o.append(f"<h2>{_esc(L['takeaways'])}</h2>")
        o.append('<ul class="takeaways">')
        o += [f"  <li>{_esc(t)}</li>" for t in note["key_takeaways"]]
        o.append("</ul>")

    o.append('<div class="footer">')
    generated_by = note.get("metadata", {}).get("generated_by", "")
    if generated_by:
        generated_at = format_generated_at(note, tz)
        suffix = f" ({generated_at})" if generated_at else ""
        o.append(f"  {_esc(L['generated'].format(by=generated_by))}{_esc(suffix)}")
    o += ["</div>", "", "</body>", "</html>", ""]
    return "\n".join(o)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("json_file", type=Path)
    parser.add_argument("-f", "--format", choices=["markdown", "html"], default="markdown")
    parser.add_argument("-o", "--output", type=Path, help="output file (default: stdout)")
    parser.add_argument("--lang", choices=sorted(LABELS), default="ja")
    parser.add_argument("--tz", default="Asia/Tokyo")
    args = parser.parse_args()

    note = json.loads(args.json_file.read_text(encoding="utf-8"))
    render = render_html if args.format == "html" else render_markdown
    output = render(note, lang=args.lang, tz=args.tz)

    if args.output:
        args.output.write_text(output, encoding="utf-8")
        print(f"compiled: {args.output}")
    else:
        print(output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
